"""add exam_date to user

Revision ID: 592e4963acc4
Revises: 6fe98bd6d589
Create Date: 2026-05-28 23:40:22.623178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '592e4963acc4'
down_revision = '6fe98bd6d589'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exam_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('exam_date')

    # ### end Alembic commands ###
