"""add custom_quote to user

Revision ID: ba03d70175b4
Revises: dd5c1c8b65e0
Create Date: 2026-05-28 23:23:33.025846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba03d70175b4'
down_revision = 'dd5c1c8b65e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_quote', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('custom_quote')

    # ### end Alembic commands ###
