"""add passage_text to exam_question

Revision ID: febc4c8b5283
Revises: d6bf4e320f09
Create Date: 2026-05-29 14:35:47.019545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'febc4c8b5283'
down_revision = 'd6bf4e320f09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam_question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('passage_text', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam_question', schema=None) as batch_op:
        batch_op.drop_column('passage_text')

    # ### end Alembic commands ###
